/*
 * GP4U social content — single source for:
 *   marketing/social/first-30-posts.md
 *   marketing/social/calendar-90-days.csv
 *   marketing/video/short-form-concepts.md
 * Edit here, then run:  node marketing/social/build-calendar.js
 *
 * EVERY medical statement below is general information drafted for GP review. Nothing is published until a GP has
 * signed it off (see marketing/compliance/compliance-checklist.md). Prices: take them from www.gp4u.ie/fees/ on the day.
 */
const TAGS = '#GP4U #OneTapRealCare #OnlineGP #IrishGP #Ireland';

// ------------------------------------------------------------------ the first 30 posts (Instagram + Facebook unless noted)
const POSTS = [
  { n: 1, platform: 'IG + FB', format: 'Single image (brand card)', pillar: 'Meet GP4U', topic: 'Welcome to GP4U',
    hook: 'One tap. Real care.',
    caption: 'Hello, Ireland 👋 We\'re GP4U — an Irish GP service run by real Irish-registered doctors.\n\nYou can see a GP online by video or phone, 7 days a week, from wherever you are in Ireland. You\'ll see the price before you book, and your GP will talk you through what happens next.\n\nOne tap. Real care.',
    cta: 'Book an online GP — link in bio', visual: 'Template "announcement": cream, badge, "One tap. Real care." in Fraunces, teal bar with gp4u.ie', tags: TAGS },
  { n: 2, platform: 'IG + FB + LinkedIn', format: 'Carousel (5 slides)', pillar: 'Meet GP4U', topic: 'What "One tap. Real care." means',
    hook: 'Three words we built GP4U around.',
    caption: '"One tap" — getting to a GP shouldn\'t take a week of phone calls.\n"Real" — real Irish-registered doctors. Not a chatbot, not a script.\n"Care" — the careful, personal approach of a good family GP, whichever way you see us.\n\nThat\'s GP4U.',
    cta: 'Follow for plain-English GP advice', visual: 'Slides: 1 slogan · 2 One tap · 3 Real · 4 Care · 5 CTA. Template "carousel"', tags: TAGS },
  { n: 3, platform: 'IG Reel + TikTok + FB', format: 'Video 30–45s (founder/GP to camera)', pillar: 'Meet GP4U', topic: 'Why GP4U exists',
    hook: '"I\'m a GP, and I built GP4U because…"',
    caption: 'Why we built GP4U, in under a minute. (Script V01 in our video library.)',
    cta: 'See how it works — link in bio', visual: 'GP at desk, natural light; captions; 3-second brand end card', tags: TAGS },
  { n: 4, platform: 'IG + FB', format: 'Carousel (6 slides)', pillar: 'Online GP explained', topic: 'How online GP works — 4 steps',
    hook: 'Seeing a GP online, step by step.',
    caption: '1️⃣ Choose a service — video, phone, repeat prescription or sick cert\n2️⃣ Tell us what\'s going on — a short, private questionnaire\n3️⃣ Pick a time and pay securely — price shown before you pay\n4️⃣ Speak to your GP — join from your phone or computer\n\nWhere your GP considers it appropriate, prescriptions go straight to the pharmacy you choose.',
    cta: 'Save this for when you need it', visual: 'Template "carousel", one step per slide, simple line icons from the website', tags: TAGS },
  { n: 5, platform: 'IG Reel + TikTok + FB', format: 'Video 30s', pillar: 'Meet GP4U', topic: 'Meet the GP',
    hook: '"Hi, I\'m Dr ___, one of the GPs at GP4U."',
    caption: 'Meet Dr ___ — [real name, role, Medical Council registration number if they agree to show it]. Ask them anything (general questions only 🙂) in the comments.',
    cta: 'Follow to meet the team', visual: 'Real GP portrait + short to-camera intro. **Only with a real, consenting doctor**', tags: TAGS, needs: 'Real GP on camera' },
  { n: 6, platform: 'IG + FB', format: 'Carousel (7 slides)', pillar: 'Online GP explained', topic: 'What an online GP can help with',
    hook: 'What can you actually see an online GP about?',
    caption: 'Lots of everyday, non-emergency concerns — for example:\n• coughs, colds and sore throats\n• skin problems like rashes, acne or eczema flare-ups\n• urine infection symptoms\n• contraception reviews\n• repeat prescriptions\n• sick certificates\n\nAnd some things need to be seen in person — your GP will tell you honestly if that\'s the case.',
    cta: 'See the full list at gp4u.ie', visual: 'Template "carousel"; last slide = "When online isn\'t right" + emergency line', tags: TAGS, review: true },
  { n: 7, platform: 'IG + FB', format: 'Carousel (6 slides)', pillar: 'GP education', topic: 'When to seek GP care — and when it\'s an emergency',
    hook: 'GP, pharmacy or 112? A quick guide.',
    caption: 'Pharmacy: minor ailments and advice on over-the-counter treatments.\nGP (online or in person): symptoms that aren\'t improving, new or ongoing problems, prescriptions, certificates.\n112 / 999 or the Emergency Department: chest pain, severe difficulty breathing, signs of a stroke, heavy bleeding, collapse, a seizure, or a severe allergic reaction.\n\nIf you\'re not sure, don\'t wait — ask.',
    cta: 'Share with someone who needs this', visual: 'Three-column "traffic light" graphic in brand colours (teal / sand / warm) — not red alarm styling', tags: TAGS, review: true },
  { n: 8, platform: 'IG + FB', format: 'Carousel FAQ (5 slides)', pillar: 'Online GP explained', topic: 'FAQ — your first online consultation',
    hook: 'Your questions about online GP, answered.',
    caption: '• Are the doctors Irish-registered? Yes.\n• Video or phone? Your choice.\n• How much? Shown before you pay — see gp4u.ie/fees.\n• Prescriptions? Where your GP considers them appropriate, sent to your chosen pharmacy.\n• Emergencies? No — call 112 or 999.',
    cta: 'More answers at gp4u.ie/faq', visual: 'Template "faq"', tags: TAGS },
  { n: 9, platform: 'IG Stories + TikTok', format: 'Behind the scenes (photos/video)', pillar: 'Behind GP4U', topic: 'Building GP4U',
    hook: 'What goes into building a GP service from scratch?',
    caption: 'Late nights, a lot of testing, and a lot of thinking about privacy. A peek behind GP4U.',
    cta: 'Follow the journey', visual: 'Laptop, notebook, whiteboard of the booking flow (no patient data), coffee', tags: TAGS },
  { n: 10, platform: 'IG + FB', format: 'Single image', pillar: 'Patient convenience', topic: 'Online GP benefits',
    hook: 'No waiting room. No time off work. A real GP.',
    caption: 'Video or phone, 7 days a week, from wherever you are in Ireland. Pick a time that suits you, see the price before you book, and speak to an Irish-registered GP.',
    cta: 'Book an online GP — link in bio', visual: 'Online GP photo (current website image until the shoot) + slogan strip', tags: TAGS },
  { n: 11, platform: 'IG + FB + TikTok', format: 'Myth vs fact (carousel / video)', pillar: 'Myth vs fact', topic: 'Online GPs can\'t prescribe',
    hook: 'Myth: "An online GP can\'t prescribe anything."',
    caption: 'Fact: Irish-registered GPs can issue prescriptions after an online consultation where they consider it clinically appropriate and safe — and send them to your chosen pharmacy. Some medicines, and some problems, need an in-person assessment first.',
    cta: 'Learn how it works', visual: 'Template "myth-fact"', tags: TAGS, review: true },
  { n: 12, platform: 'IG + FB', format: 'Carousel (6 slides)', pillar: 'GP education', topic: 'When should a cough be checked?',
    hook: 'That cough that just won\'t go…',
    caption: 'Most coughs from colds settle on their own within 3 weeks. Speak to a GP if your cough:\n• lasts more than 3 weeks\n• comes with breathlessness, chest pain or coughing up blood\n• comes with unexplained weight loss, or a fever that won\'t settle\n\nSevere difficulty breathing is an emergency — call 112 or 999.',
    cta: 'Save for cough season', visual: 'Template "education"', tags: TAGS + ' #CoughSeason', review: true },
  { n: 13, platform: 'IG + FB + TikTok', format: 'Teaser image / 10s video', pillar: 'Future clinic', topic: 'Something new is coming to Newbridge',
    hook: 'Something new is coming to Newbridge. 👀',
    caption: 'We\'re preparing something for Newbridge, Co. Kildare. More soon.\n\nWant to be first to know? Sign up at gp4u.ie (link in bio).',
    cta: 'Get opening news', visual: 'Template "clinic-teaser": cream, "Something new is coming to Newbridge." — NO photos showing the building, street or signs', tags: TAGS + ' #Newbridge #Kildare', phase2: true },
  { n: 14, platform: 'IG + FB + LinkedIn', format: 'Long caption + portrait', pillar: 'Brand content', topic: 'Brand story — why "real care" matters',
    hook: 'Every patient deserves a doctor who listens.',
    caption: '[Founder story in their own words: why they became a GP, what frustrated them about access, what GP4U is trying to fix.] Written by the founder — not ghost-written claims.',
    cta: 'Follow our story', visual: 'Founder portrait (real) or warm desk photo', tags: TAGS, needs: 'Founder story in own words' },
  { n: 15, platform: 'IG + FB', format: 'Single image', pillar: 'Online GP explained', topic: 'Booking CTA',
    hook: 'Need a GP this week?',
    caption: 'See an Irish-registered GP online by video or phone. 7 days. Prices shown before you book.',
    cta: 'Book now — link in bio', visual: 'Template "announcement" variant with booking screen mock (demo data)', tags: TAGS },
  { n: 16, platform: 'IG + FB', format: 'Carousel (5 slides)', pillar: 'GP education', topic: 'Sore throat — what helps and when to get checked',
    hook: 'Sore throat? Here\'s what a GP would tell you.',
    caption: 'Most sore throats are viral and get better within a week. Rest, fluids and simple pain relief (as directed on the pack) usually help. Speak to a GP if it isn\'t improving after a week, if you get sore throats often, or if you have a weakened immune system. Difficulty breathing or swallowing, drooling, or a muffled voice needs urgent help — call 112 or 999.',
    cta: 'Save this', visual: 'Template "education"', tags: TAGS, review: true },
  { n: 17, platform: 'IG Reel + TikTok', format: 'Video 30s', pillar: 'Online GP explained', topic: 'What happens during an online GP consultation',
    hook: '"Here\'s exactly what happens when you see me online."',
    caption: 'No mystery: you join the call from your confirmation page, we talk it through, and I explain what happens next. (Script V02.)',
    cta: 'Book an online GP', visual: 'GP to camera + screen b-roll of the confirmation page (demo booking)', tags: TAGS },
  { n: 18, platform: 'IG + FB', format: 'Single image (quote)', pillar: 'Brand content', topic: 'Quote from our GP',
    hook: '"The best consultations feel like a conversation."',
    caption: 'A line our GP says a lot — and what we try to build every consultation around. — Dr ___ [real, approved quote only]',
    cta: 'Follow for more', visual: 'Template "quote"', tags: TAGS, needs: 'Real quote approved by the GP' },
  { n: 19, platform: 'IG + FB', format: 'Carousel (6 slides)', pillar: 'GP education', topic: 'Common winter illnesses — what to do',
    hook: 'Winter bugs are here. What actually helps?',
    caption: 'Colds, flu, sore throats and tummy bugs: rest, fluids, and staying home while you\'re unwell help most. Know the signs that need a GP — and the ones that need 112/999. (Full list in the slides.)',
    cta: 'Share with your family group chat', visual: 'Template "education"', tags: TAGS + ' #WinterHealth', review: true },
  { n: 20, platform: 'IG + FB + TikTok', format: 'Myth vs fact', pillar: 'Myth vs fact', topic: 'Antibiotics and colds',
    hook: 'Myth: "Antibiotics will clear up my cold faster."',
    caption: 'Fact: colds are caused by viruses, and antibiotics don\'t work on viruses. Taking them when they\'re not needed can cause side effects and makes antibiotic resistance worse. Your GP will prescribe them when they\'re needed.',
    cta: 'Save + share', visual: 'Template "myth-fact"', tags: TAGS, review: true },
  { n: 21, platform: 'IG + FB', format: 'Single image', pillar: 'Patient convenience', topic: 'Evenings and weekends',
    hook: 'Feel unwell on a Saturday?',
    caption: 'GP4U online consultations run 7 days a week. Pick a time that suits you when you book.',
    cta: 'Book online', visual: 'Photo: weekend kitchen scene (licensed) + slogan strip', tags: TAGS },
  { n: 22, platform: 'IG + FB', format: 'Carousel', pillar: 'Online GP explained', topic: 'Sick certs online',
    hook: 'Need a sick cert? Here\'s how it works online.',
    caption: 'Book a sick certificate consultation, tell us briefly what\'s been happening, and speak to a GP. If they consider a certificate appropriate, it\'s issued to you securely. (Certificates aren\'t automatic — they\'re a GP\'s decision.)',
    cta: 'See the price at gp4u.ie/fees', visual: 'Template "carousel"', tags: TAGS },
  { n: 23, platform: 'LinkedIn', format: 'Text + image', pillar: 'Behind GP4U', topic: 'Building a new GP service in Ireland',
    hook: 'What we\'ve learned building a GP service from scratch.',
    caption: '[Founder: 3 honest lessons — e.g. privacy first, saying no to things online care shouldn\'t do, designing for older patients too.]',
    cta: 'Follow GP4U', visual: 'Founder photo or product screenshot (demo data)', tags: '#Healthcare #Ireland #GeneralPractice', needs: 'Founder input' },
  { n: 24, platform: 'IG + FB', format: 'Carousel', pillar: 'GP education', topic: 'Headaches — when to worry',
    hook: 'Most headaches aren\'t serious. These signs mean get help.',
    caption: 'Most headaches are tension-type or linked to a cold, dehydration or lack of sleep. Get urgent help (112/999) for a sudden, severe "worst ever" headache, or a headache with a stiff neck and rash, confusion, weakness, or after a head injury. See a GP for headaches that are new, getting worse, or not settling.',
    cta: 'Save this', visual: 'Template "education"', tags: TAGS, review: true },
  { n: 25, platform: 'IG + FB + TikTok', format: 'Teaser', pillar: 'Future clinic', topic: 'Renovation detail',
    hook: 'Paint samples, day one. 🎨',
    caption: 'Choosing colours for our new Newbridge clinic. Warm, calm, and nothing like a waiting room you want to leave. More soon.',
    cta: 'Get opening news — link in bio', visual: 'Close-up of paint swatches on a table — **no windows, street, signs, or landmarks**', tags: TAGS + ' #Newbridge', phase2: true },
  { n: 26, platform: 'IG + FB', format: 'Carousel', pillar: 'Online GP explained', topic: 'Repeat prescriptions online',
    hook: 'Running low on a regular medicine?',
    caption: 'If you have an established diagnosis, you can request a repeat prescription review online. Answer a few safety questions, and if your GP approves it, your prescription goes to your chosen pharmacy.',
    cta: 'gp4u.ie/online-gp/repeat-prescription', visual: 'Template "carousel"', tags: TAGS },
  { n: 27, platform: 'IG + FB', format: 'Carousel', pillar: 'GP education', topic: 'For parents: fever in children — when to get help',
    hook: 'Parents: when is a fever a worry?',
    caption: 'Fever is common in children and often a sign the body is fighting an infection. Get urgent medical help for a baby under 3 months with a temperature of 38°C or more, a child who is floppy, hard to wake, breathing fast or struggling, has a rash that doesn\'t fade under a glass, or seems to be getting worse. If in doubt, call 112/999.',
    cta: 'Save + share with parents you know', visual: 'Template "education"; no photos of real children', tags: TAGS + ' #Parenting', review: true },
  { n: 28, platform: 'IG + FB', format: 'Single image', pillar: 'Brand content', topic: 'Privacy promise',
    hook: 'Your health information is yours.',
    caption: 'We encrypt clinical records, use secure video, and never share your health information for marketing. Read how we look after your data at gp4u.ie/privacy.',
    cta: 'Read our privacy notice', visual: 'Template "quote" with lock icon', tags: TAGS },
  { n: 29, platform: 'IG Reel + TikTok', format: 'Video 15s', pillar: 'Patient convenience', topic: 'From couch to consultation',
    hook: '"Can\'t get a GP appointment this week?"',
    caption: 'Book online, pick a time, speak to a real GP. One tap. Real care. (Script V03.)',
    cta: 'Book — link in bio', visual: 'Phone tap b-roll → GP on video (actor-free: real GP or hands only)', tags: TAGS },
  { n: 30, platform: 'IG + FB + LinkedIn', format: 'Carousel', pillar: 'Meet GP4U', topic: 'Our first month — thank you',
    hook: 'One month of GP4U.',
    caption: '[Real numbers only if the owner wants to share them — otherwise: what we\'ve learned, what we\'ve improved, what\'s next (including our Newbridge clinic, opening soon).]',
    cta: 'Follow for what\'s next', visual: 'Template "announcement"', tags: TAGS, needs: 'Owner sign-off on any numbers' },
];

// ------------------------------------------------------------------ 36 short-form video concepts (TikTok / Reels / Shorts)
const VIDEOS = [
  ['V01', 'One tap. Real care. — Why we built GP4U', 'Meet GP4U', 45, '"I\'m a GP. Here\'s why I built GP4U."', 'The problem (getting to a GP), what GP4U does, what it won\'t do (emergencies), the promise.'],
  ['V02', 'What happens during an online GP consultation?', 'Online GP explained', 45, '"Here\'s exactly what happens when you see a GP online."', 'Join link, introductions, questions, advice, what can be issued, when you\'d be asked to be seen in person.'],
  ['V03', 'Can you see a GP online in Ireland?', 'Online GP explained', 15, '"Yes — you can see an Irish GP online."', 'Irish-registered, video or phone, 7 days, price upfront.'],
  ['V04', '3 reasons people delay seeing their GP', 'GP education', 30, '"Three reasons people put off seeing a GP."', 'Time off work, "it\'s probably nothing", not wanting to waste the GP\'s time — why it\'s OK to ask.'],
  ['V05', 'When should a cough be checked by a GP?', 'GP education', 45, '"That cough that won\'t go away…"', '3-week rule, red flags, emergency line.'],
  ['V06', 'Online GP vs walk-in GP — what\'s the difference?', 'Online GP explained', 45, '"Online or in person — which do you need?"', 'What suits online; what needs examination; our Newbridge clinic (opening soon).'],
  ['V07', 'Meet the people behind GP4U', 'Behind GP4U', 30, '"Meet the team."', 'Real team introductions (consent).'],
  ['V08', 'Building our new clinic in Newbridge', 'Future clinic', 20, '"Something new is coming to Newbridge."', 'Renovation details only — no location clues. PHASE 2.'],
  ['V09', 'What to have ready for an online consultation', 'Online GP explained', 30, '"Before your online GP call, have these ready."', 'Quiet private spot, list of medicines, pharmacy name, charged phone, good light for skin issues.'],
  ['V10', 'GP, pharmacy or 112?', 'GP education', 45, '"Not sure where to go? Quick guide."', 'Pharmacy vs GP vs emergency, examples.'],
  ['V11', 'Myth: antibiotics fix colds', 'Myth vs fact', 20, '"Will antibiotics help my cold?"', 'Viruses vs bacteria, resistance.'],
  ['V12', 'Sore throat: what actually helps', 'GP education', 30, '"Sore throat? Here\'s what I\'d tell you."', 'Self-care, when to see a GP, urgent signs.'],
  ['V13', 'How prescriptions reach your pharmacy', 'Online GP explained', 20, '"Where does my prescription go after an online consult?"', 'GP decides; sent to chosen pharmacy; pay for medicine at pharmacy.'],
  ['V14', 'Sick certs: how they work online', 'Online GP explained', 20, '"Need a sick cert?"', 'GP\'s decision, what details are needed.'],
  ['V15', 'Winter bugs checklist', 'GP education', 45, '"Winter bug season — what to do."', 'Rest, fluids, stay home, when to get help.'],
  ['V16', 'Headaches: when to worry', 'GP education', 45, '"Most headaches aren\'t serious, but…"', 'Red flags, emergency line.'],
  ['V17', 'Parents: fever in children', 'GP education', 60, '"Parents — let\'s talk about fever."', 'Under-3-months rule, warning signs, glass test, trust your instinct.'],
  ['V18', 'Myth: online doctors aren\'t real doctors', 'Myth vs fact', 15, '"Are online GPs \'real\' doctors?"', 'Irish-registered; check the Medical Council register.'],
  ['V19', 'A day building GP4U', 'Behind GP4U', 30, '"A day in the life of building a GP service."', 'Real day — no patient data.'],
  ['V20', 'Repeat prescriptions explained', 'Online GP explained', 30, '"Running low on a regular medicine?"', 'Established diagnosis, safety questions, GP review.'],
  ['V21', 'Hay fever that won\'t settle (seasonal — May)', 'GP education', 30, '"Tried everything for hay fever?"', 'Pharmacy options first; when a GP can help.'],
  ['V22', 'Skin rashes: send a photo?', 'Online GP explained', 30, '"Can a GP look at a rash online?"', 'Photos can help; some rashes need in-person; urgent rash signs.'],
  ['V23', 'Your privacy at GP4U', 'Brand content', 20, '"Where does your health information go?"', 'Encryption, no marketing use, GDPR rights.'],
  ['V24', 'What "Real care" means to us', 'Brand content', 30, '"Why \'real\' care?"', 'Listening, honesty, follow-up.'],
  ['V25', 'Myth: you should never "bother" your GP', 'Myth vs fact', 20, '"I don\'t want to waste the GP\'s time…"', 'Reassurance; when to ask.'],
  ['V26', 'Urine infection symptoms — when to get help', 'GP education', 30, '"Burning when you pee?"', 'Common symptoms; when online suits; red flags (fever, back pain, pregnancy, men, recurrent).'],
  ['V27', 'Contraception reviews online', 'Online GP explained', 30, '"Need your pill reviewed?"', 'How the review works; safety questions; when in person is better.'],
  ['V28', 'Travelling in Ireland and need a GP?', 'Patient convenience', 15, '"Away from home and feeling unwell?"', 'Online anywhere in Ireland; pharmacy near you.'],
  ['V29', 'Getting ready for the Newbridge clinic (team prep)', 'Future clinic', 20, '"Getting ready for something new."', 'Team training/prep — no location. PHASE 2.'],
  ['V30', 'Questions we get asked most', 'Online GP explained', 45, '"The questions everyone asks us."', 'Top 5 FAQs.'],
  ['V31', 'Stress and sleep — when to talk to a GP', 'GP education', 45, '"Not sleeping? When it\'s worth a chat."', 'General info; supports; crisis line (Samaritans 116 123; 112/999).'],
  ['V32', 'Men\'s health: the check-in men put off', 'GP education', 30, '"Lads, this one\'s for you."', 'Normalise seeing a GP; general signs worth checking.'],
  ['V33', 'Women\'s health: questions you can ask your GP', 'GP education', 30, '"You can ask your GP about this."', 'Periods, contraception, menopause symptoms — general.'],
  ['V34', 'First look inside (PHASE 3 only)', 'Future clinic', 30, '"Welcome to GP4U Newbridge."', 'Only after launch approval.'],
  ['V35', 'Behind the booking: how we built it', 'Behind GP4U', 30, '"Why our booking asks these questions."', 'Safety questions exist to keep you safe.'],
  ['V36', 'When online isn\'t the right choice', 'Online GP explained', 30, '"Sometimes I\'ll tell you to be seen in person."', 'Honesty builds trust; examples; emergency line.'],
];

module.exports = { POSTS, VIDEOS, TAGS };
